---
swagger: "2.0"
info:
  title: Sleeper Agents API Routes
  description: "This is a document containing the routes used in our API for invoice rendering"
tags:
- name: "rendering"
  description: "Routes for rendering invoices"
- name: "authentication"
  description: "Authenticating users"
schemes:
- "https"
- "http"
paths:
  /render:
    post:
      tags:
      - "rendering"
      summary: "render html, png or pdf file from an xml input"
      description: ""
      operationId: "uploadFile"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "XML Invoice file that is to be rendered"
        required: true
        schema:
          $ref: "#/definitions/XMLInvoice"
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/ApiResponse"
        405:
          description: "Invalid XML File Input"
  /registerUser:
    post:
      tags:
      - "authentication"
      summary: "register a new user to use the API"
      description: ""
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "User details to be registered"
        required: true
        schema:
          $ref: "#/definitions/UserDetails"
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/TokenReturn"
        400:
          description: |
            If any of the following are true:
            - User already exists
            - The password does not contain:
              - At least 8 characters
              - Contain one uppercase letter
              - Contain one lowercase letter
              - Contain one number
          schema:
            $ref: '#/definitions/ErrorReturn'
  /loginUser:
    get:
      tags:
      - "authentication"
      summary: "login in an existing user to retrieve their token"
      description: ""
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "User details to be registered"
        required: true
        schema:
          $ref: "#/definitions/UserDetails"
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/TokenReturn"
        400:
          description: |
            If any of the following are true:
            - User does not exist
            - The password is incorrect
          schema:
            $ref: '#/definitions/ErrorReturn'
  /deactivateUser:
    put:
      tags:
      - "authentication"
      summary: "deactivate an existing user account"
      description: ""
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "User details to be registered"
        required: true
        schema:
          $ref: "#/definitions/UserDetails"
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/EmptyReturn"
        400:
          description: |
            If any of the following are true:
            - User does not exist
            - The password is incorrect
          schema:
            $ref: '#/definitions/ErrorReturn'
securityDefinitions:
  api_key:
    type: "apiKey"
    name: "api_key"
    in: "header"
definitions:
  XMLInvoice:
    type: "object"
    properties:
      invoice:
        type: "XML file"
        language:
          type: "string"
          example: "English"
        fileTypes:
          type: "array"
          xml:
            wrapped: true
          items:
            type: "string"
            xml:
              name: "fileTypes"
  ApiResponse:
    type: "object"
    properties:
      htmlRender:
        type: "HTMLFile"
      pngRender:
        type: "PNGFile"
      pdfRender:
        type: "PDFFile"
  UserDetails:  
    type: "object"
    properties:
      username:
        type: "string"
      password:
        type: "string"
  TokenReturn:
    type: "object"
    properties:
      token:
        type: "string"
  ErrorReturn:
    type: "object"
    properties:
      error:
        type: "string"
  EmptyReturn:
    type: "object"
externalDocs:
  description: "Find out more about Swagger"
  url: "http://swagger.io"
