---
swagger: "2.0"
info:
  title: Sleeper Agents API Routes
  description: "This is a document containing the routes used in our API for invoice rendering"
tags:
- name: "rendering"
  description: "Routes for rendering invoices"
- name: "authentication"
  description: "Authenticating users"
schemes:
- "https"
- "http"
paths:
  /render:
    post:
      tags:
      - "rendering"
      summary: "render html, png or pdf file from an xml input"
      description: ""
      operationId: "uploadFile"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "XML Invoice file that is to be rendered"
        required: true
        schema:
          $ref: "#/definitions/XMLInvoice"
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/ApiResponse"
        405:
          description: "Invalid XML File Input"
  /registerUser:
    post:
      tags:
      - "authentication"
      summary: "register a new user to use the API"
      description: ""
      operationId: "uploadFile"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "User details to be registered"
        required: true
        schema:
          $ref: "#/definitions/XMLInvoice"
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/ApiResponse"
        405:
          description: "Invalid XML File Input"
securityDefinitions:
  api_key:
    type: "apiKey"
    name: "api_key"
    in: "header"
  petstore_auth:
    type: "oauth2"
    authorizationUrl: "https://petstore.swagger.io/oauth/authorize"
    flow: "implicit"
    scopes:
      read:pets: "read your pets"
      write:pets: "modify pets in your account"
definitions:
  XMLInvoice:
    type: "object"
    properties:
      invoice:
        type: "XML file"
        language:
          type: "string"
          example: "English"
        fileTypes:
          type: "array"
          xml:
            wrapped: true
          items:
            type: "string"
            xml:
              name: "fileTypes"
  ApiResponse:
    type: "object"
    properties:
      htmlRender:
        type: "HTMLFile"
      pngRender:
        type: "PNGFile"
      pdfRender:
        type: "PDFFile"
  UserDetails:  
    type: "object"
    properties:
      username:
        type: "string"
      password:
        type: "string"
  TokenReturn:
    type: "object"
    properties:
      token:
        type: "string"
externalDocs:
  description: "Find out more about Swagger"
  url: "http://swagger.io"
